version: "3.9"

services:
  app:
    build: .
    container_name: attendance-app
    env_file:
      - .env
    ports:
      - "8080:80"
    networks:
      - attendance-net

networks:
  attendance-net:
    external: true